[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "griffey"
requires-python = ">=3.10"
version = "0.1.0"
readme = "README.md"
dependencies = [
  "av>=17.0.0",
  "pandas>=2.0.0",
  "numpy>=2.0.0",
  "torch>=2.2.0",
  "torchaudio>=2.2.0",
  "torchvision>=0.17.0",
  "torchmetrics>=1.9.0",
  "pillow>=12.2.0",
  "tqdm>=4.67.3",
]

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "toml-cli"]

[tool.setuptools]
packages.find.exclude = ["test*"]
include-package-data = false
